platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.10.2

inputs:
  - name: source

params:
  SOURCE: source

run:
  path: bash
  args:
    - source/ci/scripts/go-build.sh
